  	<script src="<?=$assets_js?>jquery-3.1.1.min.js"></script>
	<script src="<?=$assets_js?>bootstrap.min.js"></script>
  	<script src="<?=$assets_js?>material.min.js"></script>
  	<script src="<?=$assets_js?>material-kit.js"></script>
  	<script src="<?=$assets_js?>jquery.dataTables.min.js"></script>
  	<script src="<?=$assets_js?>jquery.form-validator.min.js"></script>
  	<script src="<?=$assets_js?>jquery.form-validator.es.js"></script>
  	<script src="<?=$assets_js?>custom.js"></script>
  </body>
</html>	